# Generated by Django 2.1.1 on 2018-10-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addr',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('addr_shi', models.CharField(max_length=200)),
                ('addr_particular', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='companys',
            fields=[
                ('c_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_allname', models.CharField(max_length=50)),
                ('img_src', models.CharField(max_length=200)),
                ('href', models.CharField(max_length=200)),
                ('c_word', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('rongzi', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('c_lals', models.CharField(max_length=200)),
                ('position_number', models.IntegerField()),
                ('jl_timeliness', models.IntegerField()),
                ('jl_processing_time', models.CharField(max_length=50)),
                ('mspj', models.IntegerField()),
                ('last_login', models.CharField(max_length=50)),
                ('addr_heade', models.CharField(max_length=200)),
                ('intro', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='addr',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys'),
        ),
    ]
