# Generated by Django 2.1.1 on 2018-10-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='positions',
            fields=[
                ('p_name', models.CharField(max_length=30)),
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('hr_id', models.CharField(max_length=30)),
                ('img_url', models.CharField(max_length=200)),
                ('pub_date', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=30)),
                ('exp', models.CharField(max_length=50)),
                ('edu', models.CharField(max_length=50)),
                ('word_cut', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
            ],
        ),
        migrations.CreateModel(
            name='poslals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_list_type', models.CharField(max_length=200)),
                ('category_list_hot', models.CharField(max_length=200)),
                ('menu_sub', models.CharField(max_length=1000)),
            ],
        ),
    ]
