# Generated by Django 2.1.1 on 2018-10-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_auto_20181017_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poslals',
            name='menu_sub',
            field=models.CharField(max_length=1000),
        ),
    ]
