# Generated by Django 2.1.1 on 2018-10-20 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_hr_user'),
        ('position', '0003_auto_20181017_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_collection',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.positions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
