# Generated by Django 2.1.1 on 2018-10-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_position_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position_collection',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
