# Generated by Django 2.1.1 on 2018-10-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0005_auto_20181020_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='position_and_resuem',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('pr_date', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.positions')),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='position_and_resuem',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
