# Generated by Django 2.1.1 on 2018-10-17 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='manager',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=30)),
                ('m_img', models.CharField(max_length=200)),
                ('m_position', models.CharField(max_length=50)),
                ('m_intro', models.TextField(max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.companys')),
            ],
        ),
    ]
