# Generated by Django 2.1.1 on 2018-10-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hr_tel', models.CharField(max_length=30, unique=True)),
                ('hr_pwd', models.CharField(max_length=255)),
                ('hr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_tel', models.CharField(max_length=30, unique=True)),
                ('user_pwd', models.CharField(max_length=255)),
                ('regist_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
